# argocd file to deploy the application in dev namespace
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-dev
spec:
  project: default
  source:
    repoURL: https://github.com/karishma-battina/gitops-argocd
    targetRevision: main
    path: app/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  # Sync the application
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {
      prune: true,
      selfHeal: true
    }