apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-prod
spec:
  project: default
  source:
    repoURL: https://github.com/karishma-battina/gitops-argocd
    targetRevision: main
    path: app/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  # Sync the application
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {
      prune: true,
      selfHeal: true
    }