apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
patchesStrategicMerge:
  - patch.yml
namePrefix: prod-
commonLabels:
  env: prod
images:
  - name: kacr3105.azurecr.io/nginx
    newTag: v1.2