apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2  # High availability in prod
  template:
    spec:
      containers:
        - name: nginx
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
spec:
  rules:
  - host: 128.203.219.86
    http:
      paths:
      - path: /prod
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80
