apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patchesStrategicMerge:
  - patch.yml
namePrefix: dev-
commonLabels:
  env: dev
images:
  - name: kacr3105.azurecr.io/nginx
    newTag: v1.3