apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1  # Keep 1 replica for dev
  template:
    spec:
      containers:
        - name: nginx
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
