
name: 'Build on AKS'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    environment: production

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Azure Login
      uses: Azure/login@v2.2.0
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS context
      id: set-context
      uses: azure/aks-set-context@v3.0
      with:
        resource-group: '${{ secrets.resource_group }}'
        cluster-name: '${{ secrets.cluster_name }}'

    - name: Docker image build
      id: build-image
      if: ${{ github.event_name == 'push' && contains(github.event.changes, 'app/Dockerfile') }} 
      run: |
        echo "Dockerfile has changed. Running Docker build and push ..."
        docker build -t ${{ secrets.container_registry_name }}.azurecr.io/nginx:v1.0 app/
        docker login ${{ secrets.container_registry_name }}.azurecr.io -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }}
        docker push ${{ secrets.container_registry_name }}.azurecr.io/nginx:v1.0

    - name: Setup kubectl
      id: install-kubectl
      uses: azure/setup-kubectl@v4.0.0
    
    # Should we run this only once, during argocd setup?
    - name: Apply Argo CD Application
      id: apply-argocd
      if: ${{ github.event_name == 'push' && contains(github.event.changes, 'argocd.yml') }} 
      run: |
        echo ${{ github.event.changes }}
        kubectl apply -f argocd.yml -n argocd

    #- name: Deploy to AKS
    #  id: deploy-aks
    #  uses: Azure/k8s-deploy@v5
    #  with:
    #    namespace: 'argocd'
    #    manifests: |
    #       app/manifests/hello-world.yml


# Next step: 